[build]
rustflags = ["-Z", "threads=8"]

[env]
LEPTOS_OUTPUT_NAME="config_default"

[unstable]
codegen-backend = true

[profile.server-dev]
codegen-backend = "cranelift"

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" ]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/local/bin/mold", "-C", "target-feature=+sse,+sse2"]
